version: '3.1'

services:
    web:
        image: exam:latest
        restart: unless-stopped
        ports:
            - 13000:9000
        environment:
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=tictactoe
            - DB_USERNAME=root
            - DB_PASSWORD=9B6cVRLgiS4#
        extra_hosts:
            - host.docker.internal:host-gateway
